/**
 * Antigravity Agent - Content Script
 * Injected into web pages to support text selection chip, visual page fragment picker,
 * DOM analysis, and Antigravity quick interactions.
 */

(function () {
  'use strict';

  // Guard against double injection
  if (window.__antigravityContentLoaded) return;
  window.__antigravityContentLoaded = true;

  const MAX_SELECTION_CHARS = 2500;
  const MAX_FRAGMENT_CHARS = 4000;

  // ─── Agent Working Shield / Debug Overlay ──────────────────────────────────
  let workOverlay = null;
  let workFrame = null;
  let isWorkPaused = false;

  // Intercept user manual clicks during active work without blocking programmatic actions
  function onUserManualIntervention(e) {
    if (!workOverlay || isWorkPaused) return;
    const banner = document.getElementById('__antigravity_overlay_banner');
    if (banner && banner.contains(e.target)) return;
    
    // If the event is a direct user physical action (e.isTrusted === true),
    // prevent accidental user clicks from conflicting with the agent's work.
    // Programmatic synthetic events generated by automation have e.isTrusted === false or are direct DOM calls.
    if (e.isTrusted) {
      e.stopImmediatePropagation();
      e.preventDefault();
    }
  }

  function showWorkOverlay(options = {}) {
    if (workOverlay) {
      const label = document.getElementById('__antigravity_overlay_label');
      if (label && options.title) {
        label.textContent = options.title.replace(/^Code:\s*/i, '');
      }
      return;
    }

    // Outer full-screen container (pointer-events: none ensures automation clicks go straight to page elements)
    const overlay = document.createElement('div');
    overlay.id = '__antigravity_work_overlay';
    Object.assign(overlay.style, {
      position: 'fixed',
      inset: '0',
      width: '100vw',
      height: '100vh',
      zIndex: '2147483646',
      pointerEvents: 'none',
      background: 'transparent',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'flex-start',
      paddingTop: '20px',
      boxSizing: 'border-box',
      transition: 'opacity 0.25s ease',
      fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      userSelect: 'none',
    });

    // Square / Rectangular frame with rounded corners: glowing blue border gradient & 100% transparent center
    const frame = document.createElement('div');
    frame.id = '__antigravity_work_frame';
    Object.assign(frame.style, {
      position: 'fixed',
      top: '10px',
      left: '10px',
      width: 'calc(100vw - 20px)',
      height: 'calc(100vh - 20px)',
      borderRadius: '20px',
      border: '2px solid rgba(56, 189, 248, 0.85)',
      boxShadow: 'inset 0 0 55px 15px rgba(2, 132, 199, 0.55), inset 0 0 110px 30px rgba(14, 165, 233, 0.25), 0 0 25px rgba(56, 189, 248, 0.45)',
      background: 'transparent',
      pointerEvents: 'none',
      boxSizing: 'border-box',
      zIndex: '2147483645',
      transition: 'border-color 0.3s ease, box-shadow 0.3s ease',
    });

    // Top floating pill banner (interactive Pause/Resume control)
    const banner = document.createElement('div');
    banner.id = '__antigravity_overlay_banner';
    Object.assign(banner.style, {
      background: 'rgba(15, 17, 23, 0.94)',
      border: '1px solid rgba(56, 189, 248, 0.45)',
      boxShadow: '0 8px 32px rgba(0, 0, 0, 0.65), 0 0 24px rgba(56, 189, 248, 0.35)',
      borderRadius: '9999px',
      padding: '8px 20px',
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
      color: '#ffffff',
      fontSize: '13px',
      fontWeight: '500',
      backdropFilter: 'blur(12px)',
      pointerEvents: 'all', // banner is interactive!
      cursor: 'default',
    });

    // Pulsing glowing cyan dot
    const dot = document.createElement('span');
    Object.assign(dot.style, {
      width: '9px',
      height: '9px',
      borderRadius: '50%',
      background: '#38bdf8',
      boxShadow: '0 0 12px #38bdf8',
      display: 'inline-block',
      animation: 'antigravity-pulse 1.4s infinite ease-in-out',
    });

    // Text label (Strictly "Autono is working" - no "Code:" prefix)
    const label = document.createElement('span');
    label.id = '__antigravity_overlay_label';
    const cleanTitle = (options.title || 'Autono is working').replace(/^Code:\s*/i, '');
    label.textContent = cleanTitle;
    Object.assign(label.style, {
      color: '#f8fafc',
      letterSpacing: '0.2px',
      fontWeight: '600',
    });

    // Pause / Resume button
    const pauseBtn = document.createElement('button');
    pauseBtn.type = 'button';
    pauseBtn.id = '__antigravity_overlay_pause_btn';
    pauseBtn.innerHTML = '⏸ Pause';
    Object.assign(pauseBtn.style, {
      background: 'rgba(56, 189, 248, 0.16)',
      border: '1px solid rgba(56, 189, 248, 0.45)',
      color: '#38bdf8',
      borderRadius: '20px',
      padding: '4px 14px',
      fontSize: '12px',
      fontWeight: '600',
      cursor: 'pointer',
      transition: 'all 0.15s ease',
    });

    pauseBtn.addEventListener('click', (e) => {
      e.stopPropagation();
      isWorkPaused = !isWorkPaused;
      if (isWorkPaused) {
        pauseBtn.innerHTML = '▶ Resume';
        pauseBtn.style.background = 'rgba(34, 197, 94, 0.22)';
        pauseBtn.style.color = '#4ade80';
        pauseBtn.style.borderColor = 'rgba(34, 197, 94, 0.55)';
        label.textContent = 'Paused: User inspecting page';
        frame.style.borderColor = 'rgba(34, 197, 94, 0.65)';
        frame.style.boxShadow = 'inset 0 0 45px 12px rgba(34, 197, 94, 0.35), 0 0 20px rgba(34, 197, 94, 0.35)';
        chrome.runtime.sendMessage({ type: 'AGENT_WORK_PAUSED', paused: true });
      } else {
        pauseBtn.innerHTML = '⏸ Pause';
        pauseBtn.style.background = 'rgba(56, 189, 248, 0.16)';
        pauseBtn.style.color = '#38bdf8';
        pauseBtn.style.borderColor = 'rgba(56, 189, 248, 0.45)';
        label.textContent = cleanTitle;
        frame.style.borderColor = 'rgba(56, 189, 248, 0.85)';
        frame.style.boxShadow = 'inset 0 0 55px 15px rgba(2, 132, 199, 0.55), inset 0 0 110px 30px rgba(14, 165, 233, 0.25), 0 0 25px rgba(56, 189, 248, 0.45)';
        chrome.runtime.sendMessage({ type: 'AGENT_WORK_PAUSED', paused: false });
      }
    });

    // Intervene / Write button
    const writeBtn = document.createElement('button');
    writeBtn.type = 'button';
    writeBtn.id = '__antigravity_overlay_write_btn';
    writeBtn.innerHTML = '✍ Write';
    Object.assign(writeBtn.style, {
      background: 'rgba(168, 85, 247, 0.2)',
      border: '1px solid rgba(168, 85, 247, 0.55)',
      color: '#c084fc',
      borderRadius: '20px',
      padding: '4px 14px',
      fontSize: '12px',
      fontWeight: '600',
      cursor: 'pointer',
      transition: 'all 0.15s ease',
    });

    // Inline input container (initially hidden)
    const inlineInputBox = document.createElement('div');
    inlineInputBox.id = '__antigravity_inline_input_box';
    Object.assign(inlineInputBox.style, {
      display: 'none',
      alignItems: 'center',
      gap: '8px',
      marginLeft: '4px',
    });

    const inlineInput = document.createElement('input');
    inlineInput.type = 'text';
    inlineInput.id = '__antigravity_inline_input';
    inlineInput.placeholder = 'Instruction for Autono... (Press Enter to send)';
    Object.assign(inlineInput.style, {
      background: 'rgba(0, 0, 0, 0.65)',
      border: '1px solid rgba(168, 85, 247, 0.5)',
      borderRadius: '16px',
      color: '#ffffff',
      fontSize: '12px',
      padding: '4px 12px',
      outline: 'none',
      width: '260px',
      boxSizing: 'border-box',
    });

    const sendInlineBtn = document.createElement('button');
    sendInlineBtn.type = 'button';
    sendInlineBtn.innerHTML = '➤';
    Object.assign(sendInlineBtn.style, {
      background: '#9333ea',
      border: 'none',
      borderRadius: '50%',
      width: '24px',
      height: '24px',
      color: '#ffffff',
      fontSize: '11px',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    });

    function sendIntervention() {
      const text = (inlineInput.value || '').trim();
      if (!text) return;
      chrome.runtime.sendMessage({
        type: 'user_intervention',
        text,
      });
      inlineInput.value = '';
      inlineInputBox.style.display = 'none';
      writeBtn.style.display = 'inline-block';
      label.textContent = 'Instruction sent to Autono';
      setTimeout(() => {
        if (!isWorkPaused) label.textContent = cleanTitle;
      }, 2500);
    }

    sendInlineBtn.addEventListener('click', (e) => {
      e.stopPropagation();
      sendIntervention();
    });

    inlineInput.addEventListener('keydown', (e) => {
      e.stopPropagation();
      if (e.key === 'Enter') {
        sendIntervention();
      } else if (e.key === 'Escape') {
        inlineInputBox.style.display = 'none';
        writeBtn.style.display = 'inline-block';
      }
    });

    writeBtn.addEventListener('click', (e) => {
      e.stopPropagation();
      writeBtn.style.display = 'none';
      inlineInputBox.style.display = 'flex';
      setTimeout(() => inlineInput.focus(), 50);
      chrome.runtime.sendMessage({ type: 'open_side_panel' });
    });

    inlineInputBox.appendChild(inlineInput);
    inlineInputBox.appendChild(sendInlineBtn);

    banner.appendChild(dot);
    banner.appendChild(label);
    banner.appendChild(pauseBtn);
    banner.appendChild(writeBtn);
    banner.appendChild(inlineInputBox);
    overlay.appendChild(banner);

    // Keyframes style
    if (!document.getElementById('__antigravity_overlay_styles')) {
      const styleEl = document.createElement('style');
      styleEl.id = '__antigravity_overlay_styles';
      styleEl.textContent = `
        @keyframes antigravity-pulse {
          0%, 100% { opacity: 1; transform: scale(1); }
          50% { opacity: 0.4; transform: scale(0.85); }
        }
      `;
      document.head.appendChild(styleEl);
    }

    document.documentElement.appendChild(frame);
    document.documentElement.appendChild(overlay);
    workOverlay = overlay;
    workFrame = frame;

    // Attach capture event listeners to prevent accidental user clicks during autonomous actions
    window.addEventListener('click', onUserManualIntervention, true);
    window.addEventListener('mousedown', onUserManualIntervention, true);
  }

  function hideWorkOverlay() {
    window.removeEventListener('click', onUserManualIntervention, true);
    window.removeEventListener('mousedown', onUserManualIntervention, true);

    if (workOverlay) {
      workOverlay.style.opacity = '0';
      if (workFrame) workFrame.style.opacity = '0';
      setTimeout(() => {
        if (workOverlay) {
          workOverlay.remove();
          workOverlay = null;
        }
        if (workFrame) {
          workFrame.remove();
          workFrame = null;
        }
      }, 250);
    }
  }

  // ─── Interactive Page Fragment Picker (Zylo Feature) ─────────────────────────
  let pickerActive = false;
  let pickerOverlay = null;

  function stopPicker() {
    pickerActive = false;
    if (pickerOverlay) {
      pickerOverlay.remove();
      pickerOverlay = null;
    }
    document.removeEventListener('mousemove', onPickerMove, true);
    document.removeEventListener('click', onPickerClick, true);
    document.removeEventListener('keydown', onPickerKey, true);
  }

  function onPickerMove(event) {
    const target = event.target;
    if (!target || !pickerOverlay) return;
    const rect = target.getBoundingClientRect();
    Object.assign(pickerOverlay.style, {
      left: `${rect.left}px`,
      top: `${rect.top}px`,
      width: `${rect.width}px`,
      height: `${rect.height}px`,
      display: 'block',
    });
  }

  function describeElement(element) {
    if (!element) return 'elemento';
    const tag = element.tagName.toLowerCase();
    const id = element.id ? `#${element.id}` : '';
    const heading = element.querySelector('h1, h2, h3, h4')?.textContent?.trim().slice(0, 60);
    return heading ? `${tag}${id} — ${heading}` : `${tag}${id}`;
  }

  function onPickerClick(event) {
    event.preventDefault();
    event.stopPropagation();
    const target = event.target;
    stopPicker();
    if (!target) return;

    const text = (target.innerText || target.textContent || '').trim().slice(0, MAX_FRAGMENT_CHARS);
    const elementDescription = describeElement(target);

    chrome.runtime.sendMessage({
      type: 'antigravity_picked_fragment',
      text,
      element: elementDescription,
      url: window.location.href,
      title: document.title,
    });
  }

  function onPickerKey(event) {
    if (event.key === 'Escape') {
      event.preventDefault();
      stopPicker();
      chrome.runtime.sendMessage({ type: 'antigravity_picker_cancelled' });
    }
  }

  function startPicker() {
    if (pickerActive) return;
    pickerActive = true;

    const overlay = document.createElement('div');
    Object.assign(overlay.style, {
      position: 'fixed',
      display: 'none',
      zIndex: '2147483646',
      pointerEvents: 'none',
      border: '2px solid #a855f7',
      borderRadius: '6px',
      background: 'rgba(168, 85, 247, 0.15)',
      boxShadow: '0 0 0 9999px rgba(0, 0, 0, 0.25)',
      transition: 'all 60ms ease-out',
    });

    document.documentElement.appendChild(overlay);
    pickerOverlay = overlay;

    document.addEventListener('mousemove', onPickerMove, true);
    document.addEventListener('click', onPickerClick, true);
    document.addEventListener('keydown', onPickerKey, true);
  }

  // ─── Runtime Messaging ───────────────────────────────────────────────────────
  chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
    if (request.type === 'antigravity_start_picker' || request.type === 'zylo_start_picker') {
      startPicker();
      sendResponse({ success: true });
      return true;
    }

    if (request.type === 'antigravity_stop_picker' || request.type === 'zylo_stop_picker') {
      stopPicker();
      sendResponse({ success: true });
      return true;
    }

    if (request.type === 'get_screen_json') {
      if (typeof window.__extractScreenJSON === 'function') {
        sendResponse({ success: true, data: window.__extractScreenJSON() });
      } else {
        sendResponse({
          success: true,
          data: {
            title: document.title,
            url: window.location.href,
            pageContent: document.body ? document.body.innerText.slice(0, 10000) : '',
          },
        });
      }
      return true;
    }

    if (request.type === 'highlight_element') {
      const el = document.querySelector(request.selector);
      if (el) {
        el.scrollIntoView({ behavior: 'smooth', block: 'center' });
        const prevOutline = el.style.outline;
        const prevBoxShadow = el.style.boxShadow;
        el.style.outline = '3px solid #a855f7';
        el.style.boxShadow = '0 0 20px rgba(168, 85, 247, 0.8)';
        setTimeout(() => {
          el.style.outline = prevOutline;
          el.style.boxShadow = prevBoxShadow;
        }, 2500);
        sendResponse({ success: true });
      } else {
        sendResponse({ success: false, error: 'Element not found' });
      }
      return true;
    }

    if (request.type === 'SHOW_WORK_OVERLAY' || request.type === 'antigravity_show_work_overlay') {
      showWorkOverlay(request);
      sendResponse({ success: true });
      return true;
    }

    if (request.type === 'HIDE_WORK_OVERLAY' || request.type === 'antigravity_hide_work_overlay') {
      hideWorkOverlay();
      sendResponse({ success: true });
      return true;
    }
  });

  // ─── Global Keyboard Shortcuts (09 to Open, 90 to Close) ───────────────────
  let lastPressedKey = '';
  let lastKeyTime = 0;
  const heldKeys = new Set();

  function isZeroKey(e) {
    return e.key === '0' || e.code === 'Digit0' || e.code === 'Numpad0';
  }

  function isNineKey(e) {
    return e.key === '9' || e.code === 'Digit9' || e.code === 'Numpad9';
  }

  function isEditableElement(target) {
    if (!target) return false;
    const tagName = target.tagName ? target.tagName.toLowerCase() : '';
    return (
      target.isContentEditable ||
      tagName === 'input' ||
      tagName === 'textarea' ||
      tagName === 'select'
    );
  }

  window.addEventListener(
    'keydown',
    (e) => {
      // Optional fallback: Alt + Control + C or Alt + Shift + C -> Open Side Panel
      const isC = e.key === 'c' || e.key === 'C' || e.code === 'KeyC';
      const isAltCtrlC = (e.ctrlKey || e.metaKey) && e.altKey && isC;
      const isAltShiftC = e.altKey && e.shiftKey && isC;
      if (isAltCtrlC || isAltShiftC) {
        e.preventDefault();
        e.stopPropagation();
        chrome.runtime.sendMessage({ type: 'open_side_panel' });
        return;
      }

      const isEditable = isEditableElement(e.target);
      const now = Date.now();

      // Check key '0'
      if (isZeroKey(e)) {
        heldKeys.add('0');

        // Check if '9' was pressed before '0' within 750ms -> "90" (Hide/Close)
        const is90Sequence = lastPressedKey === '9' && (now - lastKeyTime < 750);
        const is90Chord = heldKeys.has('9');

        if (is90Chord || (!isEditable && is90Sequence)) {
          e.preventDefault();
          e.stopPropagation();
          lastPressedKey = '';
          chrome.runtime.sendMessage({ type: 'close_side_panel' });
          return;
        }

        lastPressedKey = '0';
        lastKeyTime = now;
        return;
      }

      // Check key '9'
      if (isNineKey(e)) {
        heldKeys.add('9');

        // Check if '0' was pressed before '9' within 750ms -> "09" (Show/Open)
        const is09Sequence = lastPressedKey === '0' && (now - lastKeyTime < 750);
        const is09Chord = heldKeys.has('0');

        if (is09Chord || (!isEditable && is09Sequence)) {
          e.preventDefault();
          e.stopPropagation();
          lastPressedKey = '';
          chrome.runtime.sendMessage({ type: 'open_side_panel' });
          return;
        }

        lastPressedKey = '9';
        lastKeyTime = now;
        return;
      }

      // Any other key resets sequential tracking
      lastPressedKey = '';
    },
    true
  );

  window.addEventListener(
    'keyup',
    (e) => {
      if (isZeroKey(e)) heldKeys.delete('0');
      if (isNineKey(e)) heldKeys.delete('9');
    },
    true
  );

  window.addEventListener('blur', () => {
    heldKeys.clear();
    lastPressedKey = '';
  });

  // Check if there is an active running task on this tab upon page load / navigation
  try {
    chrome.runtime.sendMessage({ type: 'CHECK_ACTIVE_TASK' }, (res) => {
      if (chrome.runtime.lastError) return;
      if (res && res.isRunning) {
        showWorkOverlay({ title: res.title || 'Antigravity is working' });
      }
    });
  } catch (e) {}

  console.log('⚡ Antigravity Agent content script active with fragment picker & selection chips');
})();
